name: RSS Feed Generator

on:
  schedule:
    - cron: '0 5,11,17 * * *' # odpowiada 7:00, 13:00, 19:00 czasu polskiego (UTC+2 w lecie)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run feed generator
        run: python rss_merge.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/rss.xml || echo "No changes to commit"
          git diff --cached --quiet || git commit -m "Automated update $(date -u '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
