name: Update RSS Feed

on:
  schedule:
    # Mon-Thu + Sat-Sun: co 2h od 06:00 do 24:00 CEST (czyli 04–22 UTC)
    - cron: '0 4-22/2 * * 0-4,6'

    # Piątek: okno intensywne 05:00–11:00 CEST co 30 min (03:00–09:00 UTC)
    - cron: '0,30 3-8 * * 5'   # 03:00–08:30 UTC (05:00–10:30 CEST)
    - cron: '0 9 * * 5'        # 09:00 UTC (11:00 CEST)

    # Piątek poza oknem 05–11: co 2h od 12:00 do 24:00 CEST (10–22 UTC)
    - cron: '0 10-22/2 * * 5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run feed generator
        run: python rss_merge.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/rss.xml cache.json
          git commit -m "Automated update $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
