name: Update RSS Feed

on:
  schedule:
    # Codzienne odświeżanie (czas CEST)
    - cron: '0 5 * * *'   # 07:00 CEST
    - cron: '0 11 * * *'  # 13:00 CEST
    - cron: '0 17 * * *'  # 19:00 CEST

    # Piątek co 15 minut między 7:00–12:00 CEST (czyli 5:00–10:45 UTC)
    - cron: '0 5 * * 5'
    - cron: '15 5 * * 5'
    - cron: '30 5 * * 5'
    - cron: '45 5 * * 5'
    - cron: '0 6 * * 5'
    - cron: '15 6 * * 5'
    - cron: '30 6 * * 5'
    - cron: '45 6 * * 5'
    - cron: '0 7 * * 5'
    - cron: '15 7 * * 5'
    - cron: '30 7 * * 5'
    - cron: '45 7 * * 5'
    - cron: '0 8 * * 5'
    - cron: '15 8 * * 5'
    - cron: '30 8 * * 5'
    - cron: '45 8 * * 5'
    - cron: '0 9 * * 5'
    - cron: '15 9 * * 5'
    - cron: '30 9 * * 5'
    - cron: '45 9 * * 5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run feed generator
        run: python rss_merge.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/rss.xml
          git commit -m "Automated update $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
