name: Update RSS Feed

on:
  schedule:
    - cron: '0 5 * * *'   # 07:00 CEST
    - cron: '0 11 * * *'  # 13:00 CEST
    - cron: '0 17 * * *'  # 19:00 CEST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run feed generator
        run: python rss_merge.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/rss.xml
          git commit -m "Automated update $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
